import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'
import './globals.css'
import styles from './page.module.css'
import 'slick-carousel/slick/slick.css'
import 'slick-carousel/slick/slick-theme.css'
import StyledComponentsRegistry from './styling/registry'
import { Footer } from '../widgets/Footer'
import { Header } from '../widgets/Header'
import { headerNavLinks } from '../shared/constants/texts/header-nav-items'

const manrope = Manrope({
  subsets: ['cyrillic'],
  weight: ['400', '600', '700', '800'],
})

export const metadata: Metadata = {
  title: 'Купить готовые комплекты видеонаблюдения в Новосибирске',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ru">
      <body className={manrope.className}>
        <StyledComponentsRegistry>
          <Header navLinks={headerNavLinks} />
          <main className={styles.main} id="content">
            {children}
          </main>
          <Footer />
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
